Git scripts

diff --git a/attic/git-o b/attic/git-o
--- a/attic/git-o
+++ b/attic/git-o
@@ -1,26 +1,24 @@
 #!/bin/sh
 
 # Update Git repo and pull if safe, and watch the traffic
-# Based on https://stackoverflow.com/a/3278427
 
-git remote update --prune || exit
-REMOTE=`git rev-parse @{u}` || exit
+ROOT=`git rev-parse --show-toplevel` || exit  # Fails if not a Git repo
+[ -z "$DEBUG" ] || echo "… $ROOT"
+git fetch --prune --all || exit   # Fails if no remote
+REMOTE=`git rev-parse @{u}` || exit  # Fails if not a remote-tracking branch
 LOCAL=`git rev-parse @`
 BASE=`git merge-base $LOCAL $REMOTE`
-ROOT=`git rev-parse --show-toplevel`
 
-if [[ -z $(git status --porcelain --untracked-files=no) ]]; then
-    if [ $LOCAL = $REMOTE ]; then
-        echo "✔ $ROOT"
-        exit 0
-    elif [ $LOCAL = $BASE ]; then
-        echo $ROOT
-        git merge --ff-only $REMOTE
-    elif [ $REMOTE = $BASE ]; then
-        echo "↑ $ROOT"
-    else
-        echo "⇅ $ROOT"
-    fi
-else
-    echo "! $ROOT"
+STATUS=`git status --porcelain --untracked-files=no`
+if [ -n "$STATUS" ]; then
+    echo "! $ROOT"  # Local uncommitted changes
+elif [ $LOCAL = $REMOTE ]; then  # Up to date
+    echo "✔ $ROOT"
+elif [ $LOCAL = $BASE ]; then  # What we can here for
+    echo $ROOT
+    git merge --ff-only $REMOTE
+elif [ $REMOTE = $BASE ]; then  # Need to push
+    echo "↑ $ROOT"
+else  # Diverged
+    echo "⇅ $ROOT"
 fi
